### ISSUE TITLE
Setup CI using OCaml CI

### ISSUE THREAD

**Issue by punchagan** [ocurrent/opam-ci-check#11]

**Comment by punchagan** [comment]
I've requested for the OCaml CI app to be enabled for this repo, [here](https://github.com/apps/ocaml-ci/installations/select_target)

**Comment by punchagan** [comment]
Along with this, it would be nice to enable:

- [x] Branch protection on `main`
- [x] Prevent merge commits, enforce Rebase and merge
- [x] Require code review 
- [x] Successful CI status before any merges

@shonfeder I don't seem to have the permissions to do this. Could you do this?

**Comment by shonfeder** [comment]
Added the rules! I also fixed your permissions so you should be able to do manage it in the future.

**Comment by shonfeder** [comment]
I think we have this in place now.

**Comment by punchagan** [comment]
> Added the rules! I also fixed your permissions so you should be able to do manage it in the future.

Thank you!
