### ISSUE TITLE
Add linting check to ensure an email address is provided in the `maintainer` field

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/opam-ci-check#20]
To address https://github.com/ocaml/infrastructure/issues/152

I propose we do not fuss with the opam-repo-ci code, expecting it to be replaced with the logic here shortly.

**Comment by punchagan** [comment]
@shonfeder apologies for not noticing that you had this issue assigned to yourself, and sending a PR for this.

**Comment by shonfeder** [comment]
Now worries at all. I probably shouldn't have assigned it to myself!
