### ISSUE TITLE
Prepare the project for a first release

### ISSUE THREAD

**Issue by punchagan** [ocurrent/opam-ci-check#7]
- [x] Come up with a better name than revdeps-prototype
  - Change repo name
- [x] Move to ocurrent organization
- [x] #11 
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16 
- [ ] https://github.com/ocurrent/opam-ci-check/pull/37
- [x] Add Code of Conduct.md
- [x] #22

**Comment by shonfeder** [comment]
This looks like a great initial plan: covers everything I can think of :)

>  Refactor to remove all the revdeps stuff? 

I think we can probably avoid the extra work and risk required here. But lets talk it over before committing one way or the other.

**Comment by punchagan** [comment]
> I think we can probably avoid the extra work and risk required here. But lets talk it over before committing one way or the other.

I'm comfortable leaving the revdeps stuff in, since we plan to use the CLI code as a submodule initially for faster iteration loops, before putting it out on opam.

**Comment by shonfeder** [comment]
A few simple name ideas.

1. `pkg-check (lint|revdeps|tests|...)` : because it checks the properties of a package
2. `opam-pkg-check (lint|revdeps|tests|...)` : same as above, but more clear that it is for opam
3. `opam-ci-check (lint|revdeps|tests|...)` : because it is used for the checks for `opam.ci.ocaml.org`

(3) is probably my favorite initially. Any of those sound good, or any other candidates you have in mind?

**Comment by punchagan** [comment]
> `opam-ci-check (lint|revdeps|tests|...)` : because it is used for the checks for `opam.ci.ocaml.org`

I'm happy with `opam-ci-check`. Let's go ahead with that!

**Comment by shonfeder** [comment]
Nice! In that case, I think you should be good to rename the repo and transfer it to ocurrent. Let me now if you end up needing help from me on that part tho! I'm looking forward to getting the issues you want to delegate to me :grin:

**Comment by punchagan** [comment]
> Let me now if you end up needing help from me on that part tho! 

I've been able to rename and move the repository!

> I'm looking forward to getting the issues you want to delegate to me 😁

I'll create new sub-issues and assign some of them to you. Do let me know if you have a preference for what you want to work on.

**Comment by punchagan** [comment]
>     * [x]  Add Code of Conduct.md

The ocurrent organization seems to have [adopted](https://github.com/ocaml/code-of-conduct/blob/main/list-of-adopters.md) the Code of Conduct. I'm not sure if we want/need to add the file to each repository under the organization.
